### ISSUE TITLE
JBCBJ

### ISSUE THREAD

**Issue by JHS1211** [Skaytacium/JBCBJ#2]
Hello, soldering station is great, did you finish the software? When can you share? Also have best HEX file, are looking forward to, thank you.

**Comment by JHS1211** [comment]
Hello, soldering station is great, have you finished the software? When can you share? And the best HEX file, looking forward to, thank you.

**Comment by Skaytacium** [comment]
Oh hey, sorry I forgot to reply, I've been caught up with a bunch of stuff as of now. JBCBJ is quite the side project for me. I plan on finishing it soon after I'm done with my current projects, but I wouldn't keep you on your toes. It could take a while. You could check out Unisolder till the time if you need something as of now.

Thanks for taking an interest, 
Sid
